# Generated by Django 5.2.3 on 2025-07-01 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('nome', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('curso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.FileField(upload_to='treinamento/')),
            ],
        ),
        migrations.CreateModel(
            name='Coleta_faces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roi/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_coleta', to='registro.cadastro_user')),
            ],
        ),
    ]
